kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/gcr
  settings:
    registry: gcr.io
    repo: myfirstrepo/test
    tags: latest
    json_key:
      from_secret: google_credential